edges:
- from_level: 0
  rewards:
  - 1
  - 2
  to_levels:
  - 0
- from_level: 0
  rewards:
  - 0
  to_levels:
  - 1
- from_level: 1
  rewards:
  - 1
  - 2
  to_levels:
  - 0
- from_level: 1
  rewards:
  - 1
  - 2
  to_levels:
  - 1
- from_level: 1
  rewards:
  - 0
  to_levels:
  - 2
- from_level: 2
  rewards:
  - 1
  - 2
  to_levels:
  - 0
  - 1
- from_level: 2
  rewards:
  - 1
  - 2
  to_levels:
  - 2
- from_level: 2
  rewards:
  - 0
  to_levels:
  - 3
- from_level: 3
  rewards:
  - 1
  - 2
  to_levels:
  - 0
  - 1
- from_level: 3
  rewards:
  - 1
  - 2
  to_levels:
  - 2
- from_level: 3
  rewards:
  - 2
  - 3
  to_levels:
  - 3
- from_level: 3
  rewards:
  - 4
  to_levels:
  - 4
- from_level: 4
  rewards:
  - 3
  - 4
  to_levels:
  - 3
  - 4
levels:
- color: white
  idx: 0
  is_start: true
  max_n_nodes: 3
  min_n_nodes: 3
  n_nodes: 3
- color: paleturquoise
  idx: 1
  is_start: null
  max_n_nodes: null
  min_n_nodes: 2
  n_nodes: 2
- color: lightskyblue
  idx: 2
  is_start: null
  max_n_nodes: null
  min_n_nodes: 1
  n_nodes: 1
- color: royalblue
  idx: 3
  is_start: null
  max_n_nodes: null
  min_n_nodes: 2
  n_nodes: 2
- color: blue
  idx: 4
  is_start: null
  max_n_nodes: 2
  min_n_nodes: 2
  n_nodes: 2
n_edges_per_node: 2
n_nodes: 10
n_steps: 8
rewards:
- color: red
  idx: 0
  reward: -50
- color: coral
  idx: 1
  reward: 0
- color: lightgrey
  idx: 2
  reward: 100
- color: lightgreen
  idx: 3
  reward: 200
- color: green
  idx: 4
  reward: 400
